spring.application.name=bookscout
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bookscout;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=admin
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
logging.pattern.console=[%thread] %-5level: %logger - %msg%n
logging.level.root=INFO
spring.main.banner-mode=off

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=AQUI_VA_EL_GMAIL
spring.mail.password=AQUI_VA_MI_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true