spring.application.name=bookscout

# --- BASE DE DATOS (Variables) ---
# En la nube, la URL completa te la da el proveedor, así que la hacemos variable
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# --- LOGS & CONFIG ---
logging.pattern.console=[%thread] %-5level: %logger - %msg%n
logging.level.root=INFO
spring.main.banner-mode=off
# OJO: Si usas Spring Security, quitar esta exclusión luego, pero por ahora déjala si te funciona
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# --- GMAIL (Variables) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true